basePath: /
definitions:
  handlers.Response:
    properties:
      data:
        items:
          additionalProperties: true
          type: object
        type: array
      error:
        type: string
      request_key:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: your-url.com
info:
  contact: {}
  description: This is a httpserver
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /sample:
    get:
      consumes:
      - application/json
      description: Get data
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Response'
      summary: Get data
      tags:
      - sample
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
